// Fuente unica para la pagina /success-cases (y su espejo /casos-exito).
// Refleja los arrays successCases hardcodeados en cada
// app/[locale]/casos-exito/<industria>/page.js. Si editas un caso en
// una pagina de industria, actualizalo aqui tambien, o migra esa
// pagina a importar desde este archivo en un PR posterior.

export const industries = [
  { slug: "agricola", key: "agricola" },
  { slug: "alimentos", key: "alimentos" },
  { slug: "automotriz", key: "automotriz" },
  { slug: "estudio-juridico", key: "estudioJuridico" },
  { slug: "financiero", key: "financiero" },
  { slug: "industrias-tecnologicas", key: "industriasTecnologicas" },
  { slug: "salud", key: "salud" },
  { slug: "seguros", key: "seguros" },
  { slug: "servicios-profesionales", key: "serviciosProfesionales" },
  { slug: "servicios-tecnicos", key: "serviciosTecnicos" },
  { slug: "software", key: "software" },
  { slug: "transporte", key: "transporte" },
];

export const successCases = [
  // ===== Agrícola =====
  {
    id: "agricola-1",
    categoria: "agricola",
    industry: "Agrotecnología",
    name: "Configurador de Oferta Técnica",
    challenge:
      "Generación manual de ofertas técnicas en documentos word con diferentes plantillas e información personalizada para clientes",
    solution:
      "Automatizamos la generación de documentos con ofertas de artículos para clientes a través de un formulario, eliminando el trabajo manual repetitivo.",
    results: { manualExecution: "2 hr", automatedExecution: "2 min", timeSaving: "98%" },
    tools: ["excel", "word", "pdf", "javascript"],
    platform: "rocketbot",
  },
  {
    id: "agricola-2",
    categoria: "agricola",
    industry: "Agroindustria",
    name: "Conciliación Bancaria",
    challenge: "Conciliar los movimientos de diferentes bancos argentinos y los movimientos de finnegans",
    solution: "Automatización de la descarga de movimientos de cada banco, comparación con los movimientos de finnegans y conciliación de los mismos",
    results: { manualExecution: "2 hr", automatedExecution: "5 min", timeSaving: "96%" },
    tools: ["finnegans", "excel", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "agricola-3",
    categoria: "agricola",
    industry: "Agrotecnología",
    name: "Registro de Artículos por Audio",
    challenge: "Los operarios poco técnicos en terreno, debían buscar en la base de datos los artículos para presupuestar.",
    solution: "Extracción de los articulos desde un audio enviado por el operario, y envío de la información al sistema de presupuestos.",
    results: { manualExecution: "2 hr", automatedExecution: "5 min", timeSaving: "96%" },
    tools: ["python", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "agricola-4",
    categoria: "agricola",
    industry: "Frutícola",
    name: "Carga de Facturas en ERP Quality",
    challenge: "Bajar los documentos desde el SII, y carga de cada uno junto a la respectiva orden de compra en su ERP Quality (Q-biz).",
    solution: "Automatización de la descarga de facturas del SII, búsqueda de la respectiva orden de compra y carga en ERP Quality (Q-Biz)",
    results: { manualExecution: "8 hr", automatedExecution: "1 hr", timeSaving: "87%" },
    tools: ["excel", "qbiz", "sii", "pdf", "xml", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "agricola-5",
    categoria: "agricola",
    industry: "Agrotecnología",
    name: "Generación de Planos",
    challenge: "Generación de Planos DWG e imagenes TIFF descargando archivos KMZ de diferentes plataformas incluyendo google earth",
    solution: "Automatización de la descarga de archivos KMZ y control de las aplicaciones de Google Earth, BricsCad y QGIS para generar los planos y imagenes TIFF",
    results: { manualExecution: "5 hr", automatedExecution: "25 min", timeSaving: "92%" },
    tools: ["qgis", "bricscad", "google-earth"],
    platform: "rocketbot",
  },

  // ===== Alimentos =====
  {
    id: "alimentos-1",
    categoria: "alimentos",
    industry: "Alimentos",
    name: "Mercadería OP",
    challenge: "Proceso manual de ratificación de Órdenes de Producción (OP) con validación de datos y documentación compleja.",
    solution: "Automatización del proceso de ratificación de Órdenes de Producción, incluyendo validación automática de datos y generación de documentación requerida.",
    results: { manualExecution: "4 hr", automatedExecution: "20 min", timeSaving: "92%" },
    tools: ["excel", "pdf", "dynamics"],
    platform: "rocketbot",
  },
  {
    id: "alimentos-2",
    categoria: "alimentos",
    industry: "Alimentos",
    name: "Ratificación OS",
    challenge: "Proceso manual de ratificación de Órdenes de Servicio (OS) con seguimiento de documentación y validaciones.",
    solution: "Automatización completa del proceso de ratificación de Órdenes de Servicio, incluyendo seguimiento automático de documentación y validaciones.",
    results: { manualExecution: "3 hr", automatedExecution: "15 min", timeSaving: "92%" },
    tools: ["excel", "pdf", "dynamics"],
    platform: "rocketbot",
  },
  {
    id: "alimentos-3",
    categoria: "alimentos",
    industry: "Alimentos",
    name: "Lectura de Facturas",
    challenge: "Extracción manual de información de PDFs de Cereal, Leche y Hacienda para ingreso en documentos de Compra y Venta.",
    solution: "Automatización de la extracción de información desde PDFs de diferentes sectores (Cereal, Leche, Hacienda) y su posterior ingreso en documentos de Compra y Venta.",
    results: { manualExecution: "5 hr", automatedExecution: "25 min", timeSaving: "92%" },
    tools: ["excel", "pdf", "python"],
    platform: "rocketbot",
  },

  // ===== Automotriz =====
  {
    id: "automotriz-1",
    categoria: "automotriz",
    industry: "Automotriz",
    name: "Actualización de Matrículas",
    challenge: "Actualización manual de matrículas de vehículos en diferentes sistemas (Invesfleet y MUTUA) con validación y filtrado de expedientes.",
    solution: "Automatización de la extracción de datos en Invesfleet y MUTUA, incluyendo filtrado, validación de expedientes y extracción de información del vehículo.",
    results: { manualExecution: "4 hr", automatedExecution: "15 min", timeSaving: "94%" },
    tools: ["excel", "outlook", "chrome"],
    platform: "rocketbot",
  },
  {
    id: "automotriz-2",
    categoria: "automotriz",
    industry: "Automotriz",
    name: "Descarga de Órdenes y Facturas",
    challenge: "Descarga manual de órdenes de trabajo desde el portal de Allianz para gestión de vehículos.",
    solution: "Automatización de la descarga de órdenes desde el portal de Allianz, integrando la información con el sistema de gestión vehicular.",
    results: { manualExecution: "2 hr", automatedExecution: "10 min", timeSaving: "92%" },
    tools: ["excel", "chrome", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "automotriz-3",
    categoria: "automotriz",
    industry: "Rent-a-car",
    name: "Generación de Órdenes de Compra",
    challenge: "El proceso de generación de órdenes de compra, debía cargar datos a SAP y mandar la OC al proveedor, pasando por diferentes etapas de aprobación y validación.",
    solution: "Automatización de la generación de órdenes de compra, incluyendo estandarización, carga de datos a SAP y envío de la OC al proveedor 24/7.",
    results: { manualExecution: "1 hr", automatedExecution: "2 min", timeSaving: "93%" },
    tools: ["excel", "sap", "pdf", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "automotriz-4",
    categoria: "automotriz",
    industry: "Logística",
    name: "Valoración de Baterías",
    challenge: "Valoración manual de baterías de vehículos en el portal de Allianz con verificación de estado y documentación.",
    solution: "Automatización de la valoración de baterías en el portal de Allianz, incluyendo verificación de estado, documentación y generación de reportes.",
    results: { manualExecution: "3 hr", automatedExecution: "20 min", timeSaving: "89%" },
    tools: ["excel", "chrome", "pdf", "outlook"],
    platform: "rocketbot",
  },

  // ===== Estudio Jurídico =====
  {
    id: "estudio-juridico-1",
    categoria: "estudio-juridico",
    industry: "Estudio Jurídico",
    name: "Generación de Audiencia",
    challenge: "Búsqueda manual de información de clientes deudores de bancos en diferentes webs, armado de documentos y generación de audiencias para negociación.",
    solution: "Automatización de la búsqueda de información de clientes deudores en diferentes webs, armado automático de documentos y generación de audiencias (vía calendar) para negociación con deudores.",
    results: { manualExecution: "8 hr", automatedExecution: "1 hr", timeSaving: "88%" },
    tools: ["excel", "web-scraping", "calendar", "pdf"],
    platform: "rocketbot",
  },

  // ===== Financiero =====
  {
    id: "financiero-1",
    categoria: "financiero",
    industry: "Banca",
    name: "Carga de Contratos en MIDT",
    challenge: "La página de la dirección del trabajo se cae constantemente, lo que dificulta la carga de contratos de nuevos colaboradores.",
    solution: "Automatización de carga de contratos en la página de la dirección del trabajo, incluyendo validación de datos y confirmación de envío.",
    results: { manualExecution: "5 hr", automatedExecution: "18 min", timeSaving: "94%" },
    tools: ["excel", "midt", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "financiero-2",
    categoria: "financiero",
    industry: "Seguros",
    name: "Actualización de Siniestros",
    challenge: "Buscar el estado de los siniestros abiertos en cada plataforma de seguros y actualizar la información en el portal de elevia",
    solution: "Automatización que ingresa al sistema de cada seguro, obtiene las observaciones, descarga los adjuntos y actualiza la información en el portal de elevia",
    results: { manualExecution: "4 hr", automatedExecution: "15 min", timeSaving: "94%" },
    tools: ["chrome", "reale-seguros", "mapfre", "allianz", "axa"],
    platform: "rocketbot",
  },
  {
    id: "financiero-3",
    categoria: "financiero",
    industry: "Banca",
    name: "Ratificación de Dominios",
    challenge: "Validación de dominios de correos electrónicos de contacto para documentos a ratificar.",
    solution: "Automatización de la búsqueda de dominios de correos electrónicos de contacto en los sitios de godaddy, nic chile y whois",
    results: { manualExecution: "5 hr", automatedExecution: "1 hr", timeSaving: "80%" },
    tools: ["chrome", "sharepoint"],
    platform: "rocketbot",
  },
  {
    id: "financiero-4",
    categoria: "financiero",
    industry: "Estudio Contable",
    name: "Lectura de Facturas",
    challenge: "Extracción manual de información de Facturas de Cereal, Leche y Hacienda para ingreso en documentos de Compra y Venta.",
    solution: "Automatización que recibe las facturas desde un formulario web y genera los reportes de compra, venta y bienes y servicios",
    results: { manualExecution: "1 hr", automatedExecution: "7 min", timeSaving: "88%" },
    tools: ["excel", "pdf", "outlook", "chrome"],
    platform: "rocketbot",
  },
  {
    id: "financiero-5",
    categoria: "financiero",
    industry: "Seguros",
    name: "Notificación de Siniestros",
    challenge: "Notificar por email y whatsapp a los clientes y responsables el estado de los siniestros pendientes en el software ebroker",
    solution: "Automatización de que ingresa al sistema ebroker, y notifica a los usuarios o respnsables a través de correo o whatsapp el estado de los siniestros",
    results: { manualExecution: "8 hr", automatedExecution: "1 hr", timeSaving: "88%" },
    tools: ["excel", "outlook", "ebroker", "chrome"],
    platform: "rocketbot",
  },
  {
    id: "financiero-6",
    categoria: "financiero",
    industry: "Seguros",
    name: "Gestión de tareas",
    challenge: "Resolver tareas pendientes y crear, asignar y/o actualizar siniestros en elevia y reale seguros",
    solution: "Automatización de que ingresa al sistema elevia, y según el tipo de tarea, crea, asigna y actualiza los siniestros en reale seguros",
    results: { manualExecution: "30 min", automatedExecution: "1 min", timeSaving: "97%" },
    tools: ["excel", "outlook", "reale-seguros"],
    platform: "rocketbot",
  },

  // ===== Industrias Tecnológicas =====
  {
    id: "industrias-tecnologicas-1",
    categoria: "industrias-tecnologicas",
    industry: "Industrias Tecnológicas",
    name: "Programa PDD - Industrias Tecnológicas",
    challenge: "Capacitación manual de usuarios en el Programa PDD (Programa de Desarrollo Digital) para industrias tecnológicas, proceso extenso y repetitivo.",
    solution: "Automatización del programa de capacitación PDD para industrias tecnológicas, optimizando el proceso de formación de usuarios en herramientas digitales y tecnologías emergentes.",
    results: { manualExecution: "16 hr", automatedExecution: "3 hr", timeSaving: "81%" },
    tools: ["excel", "powerpoint", "email", "web-scraping", "python"],
    platform: "rocketbot",
  },

  // ===== Salud =====
  {
    id: "salud-1",
    categoria: "salud",
    industry: "Salud",
    name: "Programa PDD - Asociación de Clínicas",
    challenge: "Capacitación manual de usuarios en el Programa PDD (Programa de Desarrollo Digital) para asociaciones de clínicas, proceso repetitivo y extenso.",
    solution: "Automatización del programa de capacitación PDD para asociaciones de clínicas, optimizando el proceso de formación de usuarios en herramientas digitales.",
    results: { manualExecution: "12 hr", automatedExecution: "2 hr", timeSaving: "83%" },
    tools: ["excel", "powerpoint", "email", "web-scraping"],
    platform: "rocketbot",
  },

  // ===== Seguros =====
  {
    id: "seguros-1",
    categoria: "seguros",
    industry: "Seguros",
    name: "Notificación de Siniestros",
    challenge: "Procesamiento manual de siniestros pendientes en Ebroker, con validación y notificación manual a clientes según medio preferido.",
    solution: "Automatización completa del procesamiento y validación de siniestros pendientes en Ebroker, notificando automáticamente al cliente según su medio preferido con mensajes predefinidos.",
    results: { manualExecution: "6 hr", automatedExecution: "30 min", timeSaving: "92%" },
    tools: ["excel", "web-scraping", "email"],
    platform: "rocketbot",
  },

  // ===== Servicios Profesionales =====
  {
    id: "servicios-profesionales-1",
    categoria: "servicios-profesionales",
    industry: "Ingeniería Vial",
    name: "Traffic Analysis",
    challenge: "Reducir el costo de revisar videos de transito manteniendo la precisión en el conteo y clasificaciónde vehiculos",
    solution: "Se construyó un sistema de IA que clasifica los vehiculos en videos de transito, generando un reporte en excel con la información consolidada.",
    results: { manualExecution: "7 días", automatedExecution: "1 día", timeSaving: "86%" },
    tools: ["python", "javascript"],
    platform: "robotipy",
  },
  {
    id: "servicios-profesionales-2",
    categoria: "servicios-profesionales",
    industry: "Software",
    name: "Gestión de Permisos",
    challenge: "Gestionar la alta y baja de usuarios en las diferentes plataformas utilizadas para gestionar proyectos",
    solution: "Automatización de las plataformas de los usuarios como Google Drive, Jira, Gmail,Slack, a partir de formularios que indican altas o bajas de acceso.",
    results: { manualExecution: "30 minutos", automatedExecution: "30 segundos", timeSaving: "98%" },
    tools: ["slack", "jira", "drive", "gmail", "github", "flokzu"],
    platform: "rocketbot",
  },
  {
    id: "servicios-profesionales-3",
    categoria: "servicios-profesionales",
    industry: "Estudio Jurídico",
    name: "Gestión administrativa",
    challenge: "Gestionar solicitudes de conciliación y audiencias extrayendo datos de correos y 6 portales como RUES y RUNT",
    solution: "Automatización optimizada para la recolección de datos, agendamiento de citas en Google Calendar y generación de informes",
    results: { manualExecution: "7 hr", automatedExecution: "30 min", timeSaving: "93%" },
    tools: ["excel", "word", "chrome"],
    platform: "rocketbot",
  },
  {
    id: "servicios-profesionales-4",
    categoria: "servicios-profesionales",
    industry: "Ingeniería y Construcción",
    name: "Descarga de Documentos SII",
    challenge: "Descarga de Facturas, Boletas de honorarios y Factoring del sistema de impuestos internos",
    solution: "Automatización de la descarga de documentos desde el sistema de impuestos internos y su posterior carga en el sistema de gestión de documentos",
    results: { manualExecution: "1 hr", automatedExecution: "5 min", timeSaving: "92%" },
    tools: ["excel", "sii"],
    platform: "rocketbot",
  },
  {
    id: "servicios-profesionales-5",
    categoria: "servicios-profesionales",
    industry: "Estudio Jurídico",
    name: "Gestión administrativa Superfinanciera",
    challenge: "Gestionar trámites ante la Superfinanciera a diario desde el portal web y extraer datos de correos para generar múltiples documentos legales",
    solution: "Automatización de la lectura de correos y la generación de documentos (Poder y Contestación), consultando en la superfinanciera, cruzando datos en Excel.",
    results: { manualExecution: "1 hr", automatedExecution: "5 min", timeSaving: "92%" },
    tools: ["excel", "word", "chrome"],
    platform: "rocketbot",
  },
  {
    id: "servicios-profesionales-6",
    categoria: "servicios-profesionales",
    industry: "Servicios Técnicos",
    name: "Carga Masiva de Artículos",
    challenge: "Búsqueda de imágenes deartículos en el sitio web de proveedores y actualización masiva de artículos en ecommerce",
    solution: "Automatización de búsqueda de imágenes de artículos con inteligencia artificial para identificar SKUs diferentes y actualización de las imagenes en el ecommerce",
    results: { manualExecution: "1 mes", automatedExecution: "2 días", timeSaving: "93%" },
    tools: ["excel", "chrome", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "servicios-profesionales-7",
    categoria: "servicios-profesionales",
    industry: "Servicios TI",
    name: "Mapeo de Tickets",
    challenge: "Consolidar manualmente múltiples reportes Excel, descargados diariamente desde correos de Outlook y el portal web Field Service",
    solution: "Automatización que filtra y descarga reportes diarios y unifica en una sola plantilla la información de los reportes",
    results: { manualExecution: "1 hr", automatedExecution: "3 min", timeSaving: "95%" },
    tools: ["excel", "chrome", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "servicios-profesionales-8",
    categoria: "servicios-profesionales",
    industry: "Servicios TI",
    name: "Gestión de Tickets",
    challenge: "Actualizar manualmente el estado de los tickets en la plataforma HELIX, extrayendo los datos desde correos pendientes en Outlook",
    solution: "Automatización que extrae el número de referencia de cada correo y accede a HELIX a diario para buscar y aplicar las actualizaciones al ticket correspondientes",
    results: { manualExecution: "1 hr", automatedExecution: "3 min", timeSaving: "95%" },
    tools: ["excel", "chrome", "outlook"],
    platform: "rocketbot",
  },

  // ===== Servicios Técnicos =====
  {
    id: "servicios-tecnicos-1",
    categoria: "servicios-tecnicos",
    industry: "Servicios Técnicos",
    name: "Carga Masiva de Artículos",
    challenge: "Carga manual masiva de artículos de proveedores en el ecommerce de SANCA, proceso repetitivo y propenso a errores.",
    solution: "Automatización completa de la carga masiva de artículos de proveedores en el ecommerce de SANCA, eliminando el trabajo manual repetitivo.",
    results: { manualExecution: "8 hr", automatedExecution: "1 hr", timeSaving: "88%" },
    tools: ["excel", "web-scraping", "ecommerce"],
    platform: "rocketbot",
  },

  // ===== Software =====
  {
    id: "software-1",
    categoria: "software",
    industry: "Software",
    name: "Gestión de Permisos Plataforma",
    challenge: "Gestión manual de permisos en plataformas como Google Drive, Jira y Slack, con altas y bajas de acceso basadas en formularios.",
    solution: "Automatización completa de la gestión de permisos en múltiples plataformas (Google Drive, Jira, Slack) a partir de formularios que indican altas o bajas de acceso.",
    results: { manualExecution: "4 hr", automatedExecution: "20 min", timeSaving: "92%" },
    tools: ["excel", "google-drive", "jira", "slack"],
    platform: "rocketbot",
  },

  // ===== Transporte =====
  {
    id: "transporte-1",
    categoria: "transporte",
    industry: "Transporte",
    name: "Expedientes Pendientes Acuse",
    challenge: "Validación manual de expedientes pendientes de acuse en la Agencia Tributaria de España, proceso lento y propenso a errores.",
    solution: "Automatización que actualiza en Dynamics NAV el estado de los expedientes pendientes de acuse en la Agencia Tributaria de España.",
    results: { manualExecution: "6 hr", automatedExecution: "30 min", timeSaving: "92%" },
    tools: ["dynamics", "chrome", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "transporte-2",
    categoria: "transporte",
    industry: "Transporte",
    name: "Expedientes Pendientes Recepción",
    challenge: "Validación manual de expedientes pendientes de recepción de acuerdo en la Agencia Tributaria de España con actualización en Dynamics.",
    solution: "Automatización de la validación de expedientes pendientes de recepción de acuerdo en la Agencia Tributaria, integrando automáticamente con Dynamics.",
    results: { manualExecution: "5 hr", automatedExecution: "25 min", timeSaving: "92%" },
    tools: ["dynamics", "chrome", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "transporte-3",
    categoria: "transporte",
    industry: "Logística",
    name: "Descarga de Estadisticas",
    challenge: "Ingresar al sistema Kipintoch e ingresar en cada módulo para descargar sus reportes (Rentabilidad, Comercial, etc)",
    solution: "Automatización de la descarga de reportes del sistema Kipintoch, permitiendo parametrizar los filtros y exportarlos en Excel",
    results: { manualExecution: "1 hr", automatedExecution: "10 min", timeSaving: "92%" },
    tools: ["chrome", "outlook", "excel"],
    platform: "uipath",
  },
  {
    id: "transporte-4",
    categoria: "transporte",
    industry: "Transporte",
    name: "Expediente Pendiente España y Portugal",
    challenge: "Envío manual de datos de expedientes de la AEAT (España) desde Dynamics NAV, incluyendo extracción, validación y firma digital.",
    solution: "Automatización completa del envío de datos de expedientes de la AEAT desde Dynamics NAV, incluyendo extracción, validación, firma digital y presentación.",
    results: { manualExecution: "8 hr", automatedExecution: "45 min", timeSaving: "91%" },
    tools: ["dynamics", "chrome", "outlook"],
    platform: "rocketbot",
  },
  {
    id: "transporte-5",
    categoria: "transporte",
    industry: "Transporte",
    name: "Vehículos Declarados",
    challenge: "Actualización manual de vehículos de Gasóleo Profesional, consultando la AEAT y extrayendo datos a Excel para importación.",
    solution: "Automatización de la actualización de vehículos de Gasóleo Profesional, consultando la AEAT, extrayendo datos a Excel e importando datos al sistema.",
    results: { manualExecution: "4 hr", automatedExecution: "20 min", timeSaving: "92%" },
    tools: ["excel", "chrome", "dynamics"],
    platform: "rocketbot",
  },
  {
    id: "transporte-6",
    categoria: "transporte",
    industry: "Transporte",
    name: "Estado Devoluciones Gasóleo Profesional",
    challenge: "Actualización manual de devoluciones de Gasóleo Profesional, consultando la AEAT por año y extrayendo datos a Excel.",
    solution: "Automatización de la actualización de devoluciones de Gasóleo Profesional, consultando la AEAT por año, extrayendo datos a Excel e importando automáticamente.",
    results: { manualExecution: "5 hr", automatedExecution: "25 min", timeSaving: "92%" },
    tools: ["dynamics", "chrome", "outlook"],
    platform: "rocketbot",
  },
];
